__author__ = 'Carlos Vigo <carviher1990@gmailcom>'
__email__ = '<carviher1990@gmailcom>'
__short_author__ = 'Carlos Vigo'
__copyright__ = '2021, Carlos Vigo'
__package_name__ = 'pdf-importer'
__module_name__ = 'pdf_importer.py'
__project_name__ = 'Statement PDF Importer'
__url__ = 'https://github.com/c-vigo/StatementPDFImporter'
__documentation__ = 'https://pdf-importer.readthedocs.io'
__version__ = '0.0.0'
__short_version__ = '0.0.0'
__description__ = 'A PDF importer to generate CSV files from bank statements'

